apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apm
  name: apm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apm
    spec:
      containers:
      - args:
        - --strict.perms=false
        - -e
        image: apm-java/apm-server:1.0.0
        name: apm
        ports:
        - containerPort: 8200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/apm-server/apm-server.yml
          name: apm-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: apm-claim0
        persistentVolumeClaim:
          claimName: apm-claim0
          readOnly: true
status: {}
